name: Deploy to Railway

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: npm install

      - name: Build
        run: npm run build

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.com/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Deploy to Railway
        env:
          RAILWAY_ENVIRONMENT_ID: ${{ secrets.RAILWAY_ENVIRONMENT_ID }}
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          SVC_ID: ${{ secrets.SVC_ID }}
        run: |
          if [ -n "${SVC_ID}" ]; then
            railway up --service "${SVC_ID}" --environment "${RAILWAY_ENVIRONMENT_ID}" 
          else
            railway up --environment "${RAILWAY_ENVIRONMENT_ID}"
          fi
